### ISSUE TITLE
Field selection/completion broken in Filter Step

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis#1295]
Filter step no longer features a dropdown containing available field names.  Autocomplete when typing does not show all fields either.

**Comment by dsimansk** [comment]
@zregvart may this be a regression from https://github.com/syndesisio/syndesis/issues/970? I'm pretty sure that your PR has fixed it.

**Comment by aileenc** [comment]
Is this an easy fix? QE would like to see it fixed in TP3.

**Comment by kcbabo** [comment]
This is a significant regression for the filter feature, so we should try for a fix in TP3.

**Comment by kcbabo** [comment]
I can confirm this is still broken in the latest tag (1.2.7).  @zregvart @gashcrumb - is there a commit with this fix that hasn't been merged into TP3 branch?  If not, any thoughts on the size/complexity of the fix?

**Comment by gashcrumb** [comment]
@kcbabo even on master I'm seeing that the property in the response that would contain the potential completions is empty on my twitter to salesforce integration, so I suspect it's going to take some troubleshooting still.

**Comment by zregvart** [comment]
We're not generating valid JSON schemas from the verifier for the data shapes. This makes inspection fail as it can't deserialize it to fetch the paths.
Trying to find a way to massage serialization of `SyndesisMetadata` so it doesn't make the JSON schema invalid.
