### ISSUE TITLE
Flacky SQL test

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#1769]
The following errors happens every third run or so, and should be fixed as it impacts our release process:

```
00:10:12.230 Tests run: 11, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.994 sec <<< FAILURE! - in io.syndesis.connector.sql.common.SqlParserTest
00:10:12.230 io.syndesis.connector.sql.common.SqlParserTest  Time elapsed: 0.109 sec  <<< ERROR!
00:10:12.230 java.sql.SQLException: Operation 'DROP TABLE' cannot be performed on object 'NAME0' because there is an open ResultSet dependent on that object.
00:10:12.230 	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.jdbc.Util.seeNextException(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
00:10:12.230 	at io.syndesis.connector.sql.common.SqlParserTest.afterClass(SqlParserTest.java:154)
00:10:12.230 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:10:12.230 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:10:12.230 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:10:12.230 	at java.lang.reflect.Method.invoke(Method.java:498)
00:10:12.230 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
00:10:12.230 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
00:10:12.230 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
00:10:12.230 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
00:10:12.230 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
00:10:12.230 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
00:10:12.230 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
00:10:12.230 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
00:10:12.230 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
00:10:12.230 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
00:10:12.230 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
00:10:12.230 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
00:10:12.230 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
00:10:12.230 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
00:10:12.230 Caused by: ERROR X0X95: Operation 'DROP TABLE' cannot be performed on object 'NAME0' because there is an open ResultSet dependent on that object.
00:10:12.230 	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
00:10:12.230 	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.verifyNoOpenResultSets(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.sql.GenericPreparedStatement.prepareToInvalidate(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.sql.depend.BasicDependencyManager.coreInvalidateFor(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.sql.depend.BasicDependencyManager.invalidateFor(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.sql.execute.DropTableConstantAction.executeConstantAction(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.sql.execute.MiscResultSet.open(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
00:10:12.230 	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
00:10:12.230 	... 22 more
00:10:12.230 

00:10:13.156 Running io.syndesis.connector.sql.stored.SqlStoredConnectorMetaDataExtensionTest
```

**Comment by zregvart** [comment]
Fixed by #1769

**Comment by rhuss** [comment]
Sorry, its is not fixed with the latest version on master. On https://ci.fabric8.io/view/release%20builds/job/syndesis-release/87/console I still see

```
00:11:58.793 io.syndesis.connector.sql.common.SqlParserTest  Time elapsed: 0.1 sec  <<< FAILURE!
00:11:58.793 java.lang.AssertionError: Exception during database cleanup.
00:11:58.793 	at io.syndesis.connector.sql.common.SqlConnectionRule.after(SqlConnectionRule.java:42)
00:11:58.793 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
00:11:58.793 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
00:11:58.793 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
00:11:58.793 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
00:11:58.793 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
00:11:58.793 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
00:11:58.793 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
00:11:58.793 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
00:11:58.793 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
00:11:58.793 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
00:11:58.793 Caused by: java.sql.SQLException: Operation 'DROP TABLE' cannot be performed on object 'NAME0' because there is an open ResultSet dependent on that object.
00:11:58.793 	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.jdbc.Util.seeNextException(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
00:11:58.793 	at io.syndesis.connector.sql.common.SqlConnectionRule.after(SqlConnectionRule.java:38)
00:11:58.793 	... 10 more
00:11:58.793 Caused by: ERROR X0X95: Operation 'DROP TABLE' cannot be performed on object 'NAME0' because there is an open ResultSet dependent on that object.
00:11:58.793 	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
00:11:58.793 	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.verifyNoOpenResultSets(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.sql.GenericPreparedStatement.prepareToInvalidate(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.sql.depend.BasicDependencyManager.coreInvalidateFor(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.sql.depend.BasicDependencyManager.invalidateFor(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.sql.execute.DropTableConstantAction.executeConstantAction(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.sql.execute.MiscResultSet.open(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
00:11:58.793 	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
00:11:58.793 	... 14 more
00:11:58.793 
00:11:59.791 Running io.syndesis.connector.sql.SqlMetadataAdapterTest
00:12:04.663 Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.87 sec - in io.syndesis.conne
```

**Comment by rhuss** [comment]
Still not fixed:

![image](https://user-images.githubusercontent.com/99080/36961165-579e4e76-204a-11e8-96ca-e3dc709cde26.png)

**Comment by rhuss** [comment]
@KurtStam nothing what could be done to reliably fix this ? 

BTW, could we restructure the tests so that not for every test case a DB is initialized  If this is easily possible than this would be a a quick win to reduce test time (currently the SQL tests lasts more than the sum of all other tests).

**Comment by rhuss** [comment]
@KurtStam When I do I release I get in 50% of the cases still

```
00:10:23.279 io.syndesis.connector.sql.common.SqlParserTest  Time elapsed: 0.102 sec  <<< FAILURE!
00:10:23.279 java.lang.AssertionError: Exception during database cleanup.
00:10:23.279 	at io.syndesis.connector.sql.common.SqlConnectionRule.after(SqlConnectionRule.java:43)
00:10:23.279 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
00:10:23.279 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
00:10:23.279 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
00:10:23.279 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
00:10:23.279 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
00:10:23.279 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
00:10:23.279 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
00:10:23.279 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
00:10:23.279 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
00:10:23.279 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
00:10:23.279 Caused by: java.sql.SQLException: Operation 'DROP TABLE' cannot be performed on object 'NAME0' because there is an open ResultSet dependent on that object.
00:10:23.279 	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
00:10:23.279 	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
00:10:23.279 	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
00:10:23.279 	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
00:10:23.279 	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
00:10:23.279 	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
00:10:23.279 	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
00:10:23.279 	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
00:10:23.279 	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
00:10:23.279 	at io.syndesis.connector.sql.common.SqlConnectionRule.after(SqlConnectionRule.java:38)
00:10:23.279 	... 10 more
00:10:23.279 Caused by: ERROR X0X95: Operation 'DROP TABLE' cannot be performed on object 'NAME0' because there is an open ResultSet dependent on that object.
00:10:23.279 	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
00:10:23.279 	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
00:10:23.279 	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.verifyNoOpenResultSets(Unknown Source)
00:10:23.279 	at org.apache.derby.impl.sql.GenericPreparedStatement.prepareToInvalidate(Unknown Source)
00:10:23.279 	at org.apache.derby.impl.sql.depend.BasicDependencyManager.coreInvalidateFor(Unknown Source)
00:10:23.279 	at org.apache.derby.impl.sql.depend.BasicDependencyManager.invalidateFor(Unknown Source)
00:10:23.279 	at org.apache.derby.impl.sql.execute.DropTableConstantAction.executeConstantAction(Unknown Source)
00:10:23.279 	at org.apache.derby.impl.sql.execute.MiscResultSet.open(Unknown Source)
00:10:23.279 	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
00:10:23.279 	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
00:10:23.279 	... 14 more
00:10:23.279 
00:10:24.206 Running io.syndesis.connector.sql.common.JSONBeanUtilTest
```

No fix available ?

**Comment by rhuss** [comment]
Can we disable the test if it can't get stabilized ?

**Comment by KurtStam** [comment]
ResultSets are supposed to close themselves, but let's see if this latest fix does the trick. 

@rhuss Since I can't reproduce it at all I'd prefer to keep the test in so that the issue gets resolved.
