### ISSUE TITLE
Syndesis logo on firefox is too large

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis#4420]
## This is a...

<pre><code>
[ ] Feature request
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Just noticed a problem with the logo - it's too large on firefox and when the side panel is displayed - it overlays the logo. On google chrome everything works as expected.

## Screenshot

![syndesis_logo](https://user-images.githubusercontent.com/4180208/52195771-8b8d3b80-2859-11e9-9236-ba0051170c8c.png)

![syndesis_logo_side_panel](https://user-images.githubusercontent.com/4180208/52195573-d3f82980-2858-11e9-8c26-3118369b2dc4.png)

## Tasks involved / Steps to Reproduce

1. Open the latest syndesis on firefox

**Comment by gashcrumb** [comment]
@jameslau Wanna look into this one?

**Comment by jameslau** [comment]
Good find @gashcrumb! I'll look into it today. Thanks!

**Comment by jameslau** [comment]
Hi @tplevko, which FF version are you using and what OS is your computer? I can't seem to reproduce the issue. I am currently on FF version Quantum and Mac OS: Mojave.

<img width="1044" alt="screen shot 2019-02-04 at 11 17 17 am" src="https://user-images.githubusercontent.com/1402829/52221221-b635bf00-286e-11e9-8f43-e326fc62f6e3.png">

**Comment by gashcrumb** [comment]
I'm personally seeing it on https://syndesis-staging.b6ff.rh-idev.openshiftapps.com and am using Firefox 65 (quantum) on Linux.

**Comment by mcoker** [comment]
Seeing it too, mac w/ FF latest v64.0.2

**Comment by tplevko** [comment]
I have the same setup as @gashcrumb - FF 65.0 on Linux

**Comment by dongniwang** [comment]
This is what I'm seeing on mine. Running on mac with FF 60.4.0.

<img width="830" alt="screen shot 2019-02-05 at 4 53 57 pm" src="https://user-images.githubusercontent.com/24943812/52306792-e496c580-2966-11e9-8bc3-7750fb6c3abf.png">

**Comment by seanforyou23** [comment]
Looks like this was fixed here https://github.com/syndesisio/syndesis/pull/4456

**Comment by kahboom** [comment]
Tried clearing cache but still seeing width as a percentage on FF here on staging (https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/) despite the changes, maybe someone else can confirm?

**Comment by dongniwang** [comment]
@tplevko - Can you please verify as well?

**Comment by tplevko** [comment]
@dongniwang with fresh syndesis install on my local minishift it works correctly for me

**Comment by zregvart** [comment]
Fixed via #4456
