### ISSUE TITLE
DB procedure name changed to text input instead of dropdown

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#5690]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
In angular the procedure name input was a dropdown that offered all available procedures within the DB. Now it's just a text input, which is more inconvenient for users to fill in and is quite error prone.

![image](https://user-images.githubusercontent.com/46345469/59343208-9bd38c80-8d0b-11e9-9134-63d859e6f5a0.png)

**Comment by gashcrumb** [comment]
This seems suspiciously similar to https://github.com/syndesisio/syndesis-react/issues/382

**Comment by riccardo-forina** [comment]
I think this is a BE related issue.

This is the-redacted-call to the API to get the action descriptor back:

```curl 'http://localhost:3000/api/v1/connections/5/actions/sql-stored-start-connector' --data-binary '{}'```

We are passing an empty object in the body because we're starting from scratch and we don't have any pre-configured value for this action.

We get back this object:
```
{
    "inputDataShape":
    {
        "kind": "none"
    },
    "outputDataShape":
    {
        "kind": "any"
    },
    "propertyDefinitionSteps":
    [
        {
            "name": "Procedure name",
            "properties":
            {
                "procedureName":
                {
                    "componentProperty": true,
                    "deprecated": false,
                    "displayName": "Procedure name",
                    "group": "producer",
                    "javaType": "java.lang.String",
                    "kind": "path",
                    "labelHint": "Name of the stored procedure.",
                    "required": true,
                    "secret": false,
                    "type": "string"
                },
                "schedulerExpression":
                {
                    "defaultValue": "60000",
                    "deprecated": false,
                    "displayName": "Period",
                    "group": "consumer",
                    "javaType": "long",
                    "kind": "parameter",
                    "labelHint": "Delay between scheduling (executing).",
                    "required": false,
                    "secret": false,
                    "type": "duration"
                },
                "template":
                {
                    "componentProperty": false,
                    "deprecated": false,
                    "displayName": "Template",
                    "group": "producer",
                    "javaType": "java.lang.String",
                    "kind": "path",
                    "labelHint": "Stored Procedure template to perform.",
                    "required": true,
                    "secret": false,
                    "type": "hidden"
                }
            },
            "description": "Select the stored procedure."
        }
    ],
    "componentScheme": "sql-stored",
    "connectorCustomizers":
    [
        "io.syndesis.connector.sql.customizer.SqlStartStoredConnectorCustomizer"
    ],
    "_meta": {}
}
```

The important bit is the `procedureName` definition, which states that the field should be a text input; there is no enum with the list of procedures here.

Maybe we're missing something in the DB? Is this related to the changes to the default schema I saw in the past few days?

**Comment by KurtStam** [comment]
It prob is related to the schema change. I will take a look.

**Comment by KurtStam** [comment]
Fixed by PR: https://github.com/syndesisio/syndesis/pull/5695

**Comment by mmuzikar** [comment]
@KurtStam didn't fix `Periodic stored procedure invocation` (when you are using DB as a start connector, the input is still text, not dropdown)

But I can confirm that non-starting connectors use dropdown now :tada:

**Comment by mmuzikar** [comment]
@KurtStam Also I just noticed if I select a procedure from the dropdown and then click on configure it's back to text input

**Comment by mmuzikar** [comment]
@KurtStam Moving this issue to inbox, because it is fixed only for one use case.

**Comment by KurtStam** [comment]
y something is fishy. The configmap `syndesis-sampledb-config` should have the following line

https://github.com/syndesisio/syndesis/blob/master/install/syndesis.yml#L565

My fresh minishift install doesn't though..

**Comment by KurtStam** [comment]
I seems to be using

https://github.com/syndesisio/syndesis/blob/master/install/operator/pkg/generator/assets/install/04-syndesis-db.yml.mustache#L40

now, which is an older version, hence the regression.

**Comment by mastepan** [comment]
@KurtStam if this is ready for QE please set Done state. Thanks.

**Comment by mmuzikar** [comment]
@KurtStam There is now a problem with `Periodic stored procedure invocation`, and when configuring already created steps.

See here: 
![Peek 2019-07-15 09-52](https://user-images.githubusercontent.com/46345469/61201976-87a5f500-a6e6-11e9-8c71-254b9dc36ee7.gif)

**Comment by heiko-braun** [comment]
@mmuzikar Please provide a textual description bug description as well. It's really hard to tell from the screenshot what you think is going wrong.

**Comment by KurtStam** [comment]
@gashcrumb it looks like the control is a text field if there is one element and a dropdown when there are 2 or more. 

To add more functions use

```
oc rsh syndesis-db-<id>
psql -U sampledb
```

and then

```
CREATE OR REPLACE FUNCTION add_lead2(
          first_and_last_name varchar,
          company varchar,
          phone varchar,
          email varchar,
          lead_source varchar,
          lead_status varchar,
          rating varchar)

          RETURNS void
          LANGUAGE 'plpgsql'

        AS $BODY$
        DECLARE
          task varchar;
        BEGIN
          task := concat(lead_status || ' ', 'Lead: Please contact ', first_and_last_name, ' from ' || company, ' via phone: ' || phone, ' via email: ' || email, '. ', 'Lead is from ' || lead_source, '. Rating: ' || rating, '.');
          insert into todo(task,completed) VALUES (task,0);
        END;
        $BODY$;

        CREATE OR REPLACE FUNCTION create_lead2(
          OUT first_name text,
          OUT last_name text,
          OUT company text,
          OUT lead_source text)
          RETURNS SETOF record
          AS
          $$
            SELECT first_name, last_name, company, lead_source
            FROM contact;
          $$
           LANGUAGE 'sql' VOLATILE;
```

**Comment by heiko-braun** [comment]
@gashcrumb @riccardo-forina Can you guys take a look at it?

**Comment by riccardo-forina** [comment]
> Is there anything we can do make it a dropdown always?

can the field always be returned with an `enum` property? I think that would be enough to render it as a select.

**Comment by gashcrumb** [comment]
@KurtStam yeah, that kinda has to happen (what @riccardo-forina said), otherwise we have no value to put in the `procedureName` field as it doesn't give us a `defaultValue` property looks like.  If you can just *always* return an `enum` for that field, then it will *always* be a select control.

Might be good actually to make it explicit too and change the `type` field for `procedureName` to `select` instead of `text`.  I'd like us to kinda move away from magic values when possible.

**Comment by zregvart** [comment]
Just say no to magic.

**Comment by heiko-braun** [comment]
@KurtStam What do you think to the proposal above? Is it a low hanging fruit?

**Comment by KurtStam** [comment]
ok thx guys, that makes sense. Will take care of it.

**Comment by heiko-braun** [comment]
For the newbies like me, is this a simple json file change in the connector meta data?

**Comment by KurtStam** [comment]
yes it should be

**Comment by zregvart** [comment]
Is this really a p0? Is there any negative side effect of this, like data loss or inability to finish designing the integration? Seems like a quirk in the UI with no major consequences to me.

**Comment by KurtStam** [comment]
So it turned out the reason this started was to support a suggest feature needed for google sheets:
https://github.com/syndesisio/syndesis/pull/5191

We decided this can now be handled using a new UI widget with the following convention:

https://issues.jboss.org/browse/FUSEDOC-2916?focusedCommentId=13754716&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13754716

**Comment by mmuzikar** [comment]
Opening for validation

**Comment by mmuzikar** [comment]
Verified by QE, but opened #6318 as a new issue appeared.
