### ISSUE TITLE
[1.7.1] Unable to create any connection

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#5831]
## This is a...

<pre><code>
[ ] Feature request
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When trying to create any connection in the ui, the "configure connection" always ends with `Something is wrong` page:

![screenshot-2019-06-20_08:31:37](https://user-images.githubusercontent.com/7081216/59826180-0c932e00-9336-11e9-8a73-72cd2372ba17.png)
![screenshot-2019-06-20_08:32:54](https://user-images.githubusercontent.com/7081216/59826181-0e5cf180-9336-11e9-8d70-1a9ff6da0564.png)
![screenshot-2019-06-20_08:33:17](https://user-images.githubusercontent.com/7081216/59826185-1026b500-9336-11e9-8f50-8373e7a0ff82.png)

**Comment by tplevko** [comment]
@heiko-braun @paoloantinori QE is blocked by this

**Comment by zregvart** [comment]
Anything in the server logs?

**Comment by tplevko** [comment]
Server log attached. I deployed from latest, but the problems seems to be the same there:
[server.log](https://github.com/syndesisio/syndesis/files/3309370/server.log)

**Comment by avano** [comment]
yeah, it is the same log as in 1.7.1

**Comment by zregvart** [comment]
I think I found the issue, it's fixed in #5747 I'll just port over the bits needed to fix it here. We should avoid invoking `POST /api/v1/connectors/{id}/credentials` for non-OAuth-capable connectors.

**Comment by mcada** [comment]
Looks like the fix does not work, I am still not able to create a connection on 1.7.2 tag.

**Comment by zregvart** [comment]
Turns out that `am` here:

https://github.com/syndesisio/syndesis/blob/8868f5d144cef161dad4cf57072d1396aad2ba8f/app/ui-react/packages/api/src/useConnectorCredentials.tsx#L8

is undefined when `GET /api/v1/connectors/{id}/credentials` response is `{}`.

I'm tempted to remove the whole `transformResponse`, but since that bit looks quite deliberate I'm not sure if I'm missing something.
